{
 "title": "Kubernetes Container",
 "description": "Summary metrics about containers running on Kubernetes nodes.",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_node_info, kubernetes_cluster)"
   },
   {
    "name": "node",
    "query": "label_values(kube_node_info{kubernetes_cluster=~\"$cluster\"}, node)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{kubernetes_cluster=~\"$cluster\", node=~\"$node\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{kubernetes_cluster=~\"$cluster\", node=~\"$node\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values(kube_pod_container_info{kubernetes_cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Pod Filtering", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "raintank-kubernetes-podnav-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "Total memory usage of containers across a cluster",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"$pod\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}",
     "target": "groupByNode(exclude(snap.$cluster.$node.grafanalabs.cadvisor.container.$namespace.$pod.*.mem.usage, 'POD'), 8, 'sum')"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod_name=~\"$pod\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}",
     "target": "groupByNode(perSecond(exclude(snap.$cluster.$node.grafanalabs.cadvisor.container.$namespace.$pod.*.cpu.total.usage, 'POD')), 8, 'sum')"
    }
   ]
  },
  {
   "title": "Network Traffic (Inbound)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod_name=~\"$pod\", kubernetes_io_hostname=~\"$node\"}[2m])",
     "legendFormat": "{{ pod_name }}",
     "target": "groupByNode(perSecond(snap.$cluster.$node.grafanalabs.cadvisor.container.$namespace.$pod.*.iface.*.in_bytes), 7, 'sum')"
    }
   ]
  },
  {
   "title": "Network Traffic (Outbound)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod_name=~\"$pod\", kubernetes_io_hostname=~\"$node\"}[2m])",
     "legendFormat": "{{ pod_name }}",
     "target": "groupByNode(perSecond(snap.$cluster.$node.grafanalabs.cadvisor.container.$namespace.$pod.*.iface.*.out_bytes), 7, 'sum')"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_io_time_seconds_total{pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{pod_name}}",
     "target": "groupByNode(perSecond(exclude(snap.$cluster.$node.grafanalabs.cadvisor.container.$namespace.$pod.*.diskio.*.reads, 'POD')), 8, 'sum')"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_write_seconds_total{pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{ pod_name }}",
     "target": "groupByNode(perSecond(exclude(snap.$cluster.$node.grafanalabs.cadvisor.container.$namespace.$pod.*.diskio.*.writes, 'POD')), 8, 'sum')"
    }
   ]
  }
 ]
}